name: zal
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+19

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.17.0
  file: ^6.1.4
  cloud_firestore: ^4.3.1
  path_provider: ^2.1.0
  shared_preferences: ^2.0.9
  sizer: ^2.0.13
  firebase_analytics: ^10.1.0
  flex_color_scheme: ^7.3.1
  settings_ui: ^2.0.2
  dependency_validator: ^3.0.0
  firebase_core: ^2.19.0
  pull_to_refresh: ^2.0.0
  package_info_plus: ^4.1.0
  upgrader: ^6.0.1
  in_app_purchase: ^3.1.5
  purchases_flutter: ^6.0.0
  google_fonts: ^4.0.4
  firebase_messaging: ^14.6.3
  font_awesome_flutter: ^10.4.0
  flutter_riverpod: ^2.3.5
  assorted_layout_widgets: ^8.0.4
  socket_io_client: ^2.0.3+1
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_gauges: ^21.2.4
  flutter_staggered_grid_view: ^0.7.0
  http: ^0.13.6
  animated_text_kit: ^4.2.2
  collection: ^1.17.1
  google_mobile_ads: ^3.0.0
  in_app_review: ^2.0.6
  loader_overlay: ^2.3.2
  timeago: ^3.3.0
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  firebase_database: ^10.3.1
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.3.0
  fl_chart: ^0.66.2
  introduction_screen: ^3.1.12
  peerdart: ^0.5.2
  logger: ^2.0.2+1
  color_print: ^1.0.3
  sidebarx: ^0.16.3
  open_file: ^3.3.2
  animated_bottom_navigation_bar: ^1.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_gemini: ^2.0.3

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  lints: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 300
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
          weight: 400
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
